minimumReleaseAge: 1440
trustPolicyIgnoreAfter: 525600
shellEmulator: true
trustPolicy: no-downgrade
overrides:
  vite: ">=8.0.14"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
patchedDependencies:
  vite-plugin-checker@0.14.1: patches/vite-plugin-checker@0.14.1.patch
