/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementRouteImport } from './routes/announcement'
import { Route as AnnouncementGameRouteImport } from './routes/announcement.$game'
import { Route as ApiAnnouncementGameRouteImport } from './routes/api.announcement.$game'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementRoute = AnnouncementRouteImport.update({
  id: '/announcement',
  path: '/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementGameRoute = AnnouncementGameRouteImport.update({
  id: '/$game',
  path: '/$game',
  getParentRoute: () => AnnouncementRoute,
} as any)
const ApiAnnouncementGameRoute = ApiAnnouncementGameRouteImport.update({
  id: '/api/announcement/$game',
  path: '/api/announcement/$game',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteWithChildren
  '/announcement/$game': typeof AnnouncementGameRoute
  '/api/announcement/$game': typeof ApiAnnouncementGameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteWithChildren
  '/announcement/$game': typeof AnnouncementGameRoute
  '/api/announcement/$game': typeof ApiAnnouncementGameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteWithChildren
  '/announcement/$game': typeof AnnouncementGameRoute
  '/api/announcement/$game': typeof ApiAnnouncementGameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/announcement' | '/announcement/$game' | '/api/announcement/$game'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/announcement' | '/announcement/$game' | '/api/announcement/$game'
  id:
    | '__root__'
    | '/'
    | '/announcement'
    | '/announcement/$game'
    | '/api/announcement/$game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementRoute: typeof AnnouncementRouteWithChildren
  ApiAnnouncementGameRoute: typeof ApiAnnouncementGameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement': {
      id: '/announcement'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof AnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement/$game': {
      id: '/announcement/$game'
      path: '/$game'
      fullPath: '/announcement/$game'
      preLoaderRoute: typeof AnnouncementGameRouteImport
      parentRoute: typeof AnnouncementRoute
    }
    '/api/announcement/$game': {
      id: '/api/announcement/$game'
      path: '/api/announcement/$game'
      fullPath: '/api/announcement/$game'
      preLoaderRoute: typeof ApiAnnouncementGameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnnouncementRouteChildren {
  AnnouncementGameRoute: typeof AnnouncementGameRoute
}

const AnnouncementRouteChildren: AnnouncementRouteChildren = {
  AnnouncementGameRoute: AnnouncementGameRoute,
}

const AnnouncementRouteWithChildren = AnnouncementRoute._addFileChildren(
  AnnouncementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementRoute: AnnouncementRouteWithChildren,
  ApiAnnouncementGameRoute: ApiAnnouncementGameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
